name: tictactoebetclic
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.3.0
  json_annotation: ^4.9.0
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3
  freezed_annotation: ^3.1.0
  flex_color_scheme: ^8.3.1
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.5.4
  custom_lint: ^0.8.0
  json_serializable: ^6.9.5
  freezed: ^3.1.0
  flutter_gen: ^5.12.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launch_icon.png"
  adaptive_icon_background: "#FF71D3ED" # Transparent
  adaptive_icon_foreground: "assets/launch_icon.png"
  remove_alpha_ios: true
